# Generated by Django 5.2 on 2025-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
