# Generated by Django 5.2 on 2025-05-01 13:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0005_privacypolicy_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleaning_service.servicetype'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 16, 35, 29, 905153)),
        ),
    ]
