# Generated by Django 5.2 on 2025-05-01 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0006_vacancy_job_type_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 16, 43, 21, 604528)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleaning_service.servicetype'),
        ),
    ]
