# Generated by Django 5.2 on 2025-05-02 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0009_alter_client_user_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 15, 2, 34, 824982)),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
