# Generated by Django 5.2 on 2025-05-02 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0010_alter_faq_answer_date_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 17, 15, 6, 24323)),
        ),
    ]
