# Generated by Django 5.2 on 2025-05-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0011_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 14, 39, 12, 562365)),
        ),
    ]
