# Generated by Django 5.2 on 2025-05-08 14:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0012_client_timezone_staff_timezone_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+375(:?44|29|33)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 14, 7, 14, 731800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+375(:?44|29|33)\\d{7}$')]),
        ),
    ]
