# Generated by Django 5.2 on 2025-05-10 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0014_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 9, 53, 24, 664534, tzinfo=datetime.timezone.utc)),
        ),
    ]
