# Generated by Django 5.2 on 2025-05-10 10:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0015_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 10, 25, 19, 448209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cleaning_service.client'),
        ),
    ]
