# Generated by Django 5.2 on 2025-05-13 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0016_alter_faq_answer_date_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logged_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 13, 31, 18, 9221, tzinfo=datetime.timezone.utc)),
        ),
    ]
