# Generated by Django 5.2 on 2025-05-10 16:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0016_alter_faq_answer_date_alter_order_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 16, 41, 53, 131749, tzinfo=datetime.timezone.utc)),
        ),
    ]
