# Generated by Django 5.2 on 2025-05-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0019_alter_client_user_alter_faq_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 19, 9, 16, 491139, tzinfo=datetime.timezone.utc)),
        ),
    ]
