# Generated by Django 5.2 on 2025-09-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_service', '0017_client_logged_in_alter_faq_answer_date'),
        ('cleaning_service', '0020_alter_faq_answer_date'),
    ]

    operations = [
    ]
